ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS balance DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS subtype VARCHAR(50);
ALTER TABLE tax_rates ADD COLUMN IF NOT EXISTS accountId VARCHAR(50);
ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'posted';
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Draft';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS isForeign TINYINT(1) DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'LKR';
