ALTER TABLE inventory 
ADD COLUMN uom VARCHAR(50) DEFAULT 'pcs',
ADD COLUMN suppliers LONGTEXT,
ADD COLUMN location VARCHAR(255),
ADD COLUMN reorderLevel INT DEFAULT 0,
ADD COLUMN createdAt DATETIME NULL DEFAULT NULL,
ADD COLUMN updatedAt DATETIME NULL DEFAULT NULL;